### ISSUE TITLE
You

### ISSUE THREAD

**Issue by WarpWing** [iyera2/Final#1]
You are the issue.

**Comment by EnderBro1000** [comment]
agreed

**Comment by Nizamovpl** [comment]
To be genuine Arjun, we appreciate ya. :D  You're an epic coder.

**Comment by WarpWing** [comment]
> To be genuine Arjun, we appreciate ya. :D You're an epic coder.

OR DO WE. BUH BUH BUH

**Comment by iyera2** [comment]
LOL

**Comment by iyera2** [comment]
Warp reponses though

**Comment by Nizamovpl** [comment]
Your responses are so insightful Arjun, really says a lot about the current issue

**Comment by WarpWing** [comment]
> Your responses are so insightful Arjun, really says a lot about the current issue

Not to worry you all but we live in a society

**Comment by Nizamovpl** [comment]
> > Your responses are so insightful Arjun, really says a lot about the current issue
> 
> Not to worry you all but we live in a society

Warp, not to worry you but you think.

**Comment by WarpWing** [comment]
> > > Your responses are so insightful Arjun, really says a lot about the current issue
> > 
> > 
> > Not to worry you all but we live in a society
> 
> Warp, not to worry you but you think.

That violates the Geneva Convention FOOOL

**Comment by Nizamovpl** [comment]
> > > > Your responses are so insightful Arjun, really says a lot about the current issue
> > > 
> > > 
> > > Not to worry you all but we live in a society
> > 
> > 
> > Warp, not to worry you but you think.
> 
> That violates the Geneva Convention FOOOL

Only to you

**Comment by WarpWing** [comment]
> > > > > Your responses are so insightful Arjun, really says a lot about the current issue
> > > > 
> > > > 
> > > > Not to worry you all but we live in a society
> > > 
> > > 
> > > Warp, not to worry you but you think.
> > 
> > 
> > That violates the Geneva Convention FOOOL
> 
> Only to you


https://user-images.githubusercontent.com/28925758/102800471-ea8ec780-4381-11eb-9231-f64892ac559f.mp4

**Comment by iyera2** [comment]
Wow, these comments are really weird.  And then video though.

**Comment by WarpWing** [comment]
> Wow, these comments are really weird. And then video though.

The video is beautiful

**Comment by iyera2** [comment]
Ya, that's true.  Doesn't make it any less weird.
